<a href="https://colab.research.google.com/github/Emyfoton/Codigos_pregrado/blob/main/Taller0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pint
!pip install pint uncertainties
import uncertainties
from uncertainties import ufloat
import pint as pint
ureg=pint.UnitRegistry(auto_reduce_dimensions=True)
Measurement=ureg.Measurement
Quantity=ureg.Quantity

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 2.0 MB/s eta 0:00:00


In [ ]:
A = ufloat(66.24,0.19) * ureg.parse_expression('cm^2')
m = ufloat(485.4,0.08) * ureg.parse_expression('g')

In [ ]:
import numpy as np
r = (A/(np.pi*4))**(1/2)
r

<Quantity(2.29591+/-0.00329, 'centimeter')>

In [ ]:
d = 2*r
d

<Quantity(4.59182+/-0.00659, 'centimeter')>

In [ ]:
V = (4*np.pi*(r**3))/3
V

<Quantity(50.6937+/-0.2181, 'centimeter ** 3')>

In [ ]:
Rho = m/V
Rho

<Quantity(9.57515+/-0.04123, 'gram / centimeter ** 3')>

In [ ]:
RhoFe = ufloat(7.87,0.08) * ureg.parse_expression('g/cm^3')
RhoFe
RhoPb = ufloat(11.34,0.11) * ureg.parse_expression('g/cm^3')
RhoPb

<Quantity(11.3400+/-0.1100, 'gram / centimeter ** 3')>

In [ ]:
mFe= RhoFe * V
mFe

<Quantity(398.960+/-4.404, 'gram')>

In [ ]:
porciFe=(mFe/m)*100
porciFe


<Quantity(82.1919+/-0.9074, 'dimensionless')>

In [ ]:
mPb= RhoPb * V
mPb

<Quantity(574.867+/-6.100, 'gram')>

In [ ]:
porciPb= (mPb/m)*100
porciPb

<Quantity(118.432+/-1.257, 'dimensionless')>

In [ ]:
Rhoaire = Quantity(1.20458,'kg/m^3')
Cd = ufloat(4.4,0.1)

In [ ]:
A=A.to_base_units()
A
Alpha = (0.5)*(Cd*Rhoaire)*A
Alpha

<Quantity(0.0175541+/-0.0004021, 'kilogram / meter')>

In [ ]:
m = m.to_base_units()
m
Beta = Alpha/m
Beta

<Quantity(0.0361642+/-0.0008285, '1 / meter')>

In [ ]:
g = Quantity(9.773,'m/s^2')
y0 = ufloat(10,0.1) * ureg.parse_expression('m')

g_magnitude = g.magnitude
g_units = g.units
g = ufloat(g_magnitude, 0) * g_units

from uncertainties.umath import acosh, exp, sqrt

tdrag = (acosh(exp(Beta.n*y0.n)))/((Beta*g)**(1/2))
tdrag

<Quantity(1.51812+/-0.01739, 'second')>

In [ ]:
t = ((2*y0)/g)**(1/2)
t

<Quantity(1.43054+/-0.00715, 'second')>

In [ ]:
#Test z:

Z = (np.abs(t.n - tdrag.n))/tdrag.s
Z

# Valor P:

from scipy.special import erfc
p = erfc(12./np.sqrt(2))*100

Z,p

(5.036545294081317, 4.740089852969541e-05)

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import os

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

os.chdir("/content/drive/MyDrive/Ondas")
!ls
file = '/content/drive/MyDrive/Ondas/free_ball (1).csv'
df = pd.read_csv(file, header=None, names=["0.00", "10.02", "0.03"])
df

Mounted at /content/drive
 datos_Fourier.csv	'Exp 02 - Errores.zip'	    'free_ball (1).csv'
 datos_no_lineales.csv	'Exp2 - Ondas Dinoemy.pdf'


0.00  10.02  0.03
0   0.00  10.02  0.03
1   0.05   9.97  0.03
2   0.10  10.00  0.03
3   0.15   9.99  0.03
4   0.20   9.79  0.03
5   0.25   9.78  0.03
6   0.30   9.56  0.03
7   0.35   9.39  0.03
8   0.40   9.20  0.03
9   0.45   9.02  0.03
10  0.50   8.74  0.04
11  0.55   8.58  0.04
12  0.60   8.30  0.04
13  0.65   8.00  0.04
14  0.70   7.73  0.04
15  0.75   7.34  0.04
16  0.80   6.97  0.05
17  0.85   6.51  0.05
18  0.90   6.17  0.05
19  0.95   5.78  0.06
20  1.00   5.35  0.06
21  1.05   4.85  0.06
22  1.10   4.49  0.07
23  1.15   4.04  0.07
24  1.20   3.48  0.08
25  1.25   2.96  0.08
26  1.30   2.50  0.09
27  1.35   1.84  0.09
28  1.40   1.35  0.10
29  1.45   0.78  0.10

In [ ]:
tiempo = df['0.00']
altura = df['10.02']
sigma = df['0.03']

tiempopy = np.array([*tiempo])
alturapy = np.array([*altura])
sigmapy = np.array([*sigma])

In [ ]:
from scipy.optimize import curve_fit

def modelofricc(t,H,B,G):
  return H - (1/B)*np.log(np.cosh(t*np.sqrt((B*G))))

popt, pcov = curve_fit(modelofricc, tiempopy, alturapy, sigma=sigmapy,p0=[5,0.001,10])
popt
errores = np.sqrt(np.diag(pcov))
popt, errores

(array([10.02656326,  0.04224917,  9.97752472]),
 array([0.01218213, 0.00546572, 0.12323489]))

In [ ]:
def modelosinfricc(t,H,G):
  return H - (G*t**2)/2

popt, pcov = curve_fit(modelosinfricc, tiempopy, alturapy, sigma=sigmapy, p0=[10,12])
popt
errores2 = np.sqrt(np.diag(pcov))
popt, errores2

(array([9.97226939, 9.09156769]), array([0.01865298, 0.06972977]))